//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.08 at 05:12:26 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/players", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model.soap;
