server: 
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    throw-exception-if-no-handler-found: true
    contentnegotiation:
      favor-path-extension: false
      favor-parameter: false
      ignore-unknown-path-extensions: true
      default-media-type: application/json

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.apache.shiro.spring.config.web.autoconfigure.ShiroWebAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/hangman?createDatabaseIfNotExist=true
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: hangman

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  baselineVersion: '1'
  default_schema: hangman
  schemas: hangman
