server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

logging:
  level:
    org.springframework.web: DEBUG
